### Park a car
POST https://localhost:5001/api/ParkingLot/ABC123/in

### Pay for parking
POST https://localhost:5001/api/ParkingLot/ABC123/payment

### Car leaving parking lot
POST https://localhost:5001/api/ParkingLot/ABC123/out